### ISSUE TITLE
websocket-related crash on the publishing app 

### ISSUE THREAD

**Issue by VladimirAkopyan** [quickbird-uk/QuickbirdUWPDashboard#83]
The app on the tablet crashes sometimes while publishing data, happens every 10 hours or so. 
The stack-trace form the store says it's related to the web-socket class, which is entirely feasible. 
[stackTrace.txt](https://github.com/quickbird-uk/QuickbirdUWPDashboard/files/1360567/stackTrace.txt)

**Comment by VladimirAkopyan** [comment]
Example of crash from the Tablet, compiled to native
[Log-171007-222244395.zip](https://github.com/quickbird-uk/QuickbirdUWPDashboard/files/1366440/Log-171007-222244395.zip)

**Comment by VladimirAkopyan** [comment]
Found the bug, by running the app in Visual Studio for a long time:
Crash report:
```
   at Windows.Storage.Streams.DataWriter.DetachStream()
   at Quickbird.Internet.WebSocketConnection.CleanUp()
   at Quickbird.Internet.WebSocketConnection.MessageRecieved(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
```
related code:
```C#
private void CleanUp()
{
	_ReconnectTimer?.Dispose();

	try
	{
		_webSocket?.Close(1000, SocketCloseMessage);
	}
	catch (Exception ex)
	{
		LoggingService.LogInfo($"Closing Websocket Failed, {ex.ToString()}", Windows.Foundation.Diagnostics.LoggingLevel.Error);
	}

	_messageWriter?.DetachStream();
	_messageWriter?.Dispose();
	_messageWriter = null;

	_webSocket?.Dispose();
	_webSocket = null;
}   
```

**Comment by VladimirAkopyan** [comment]
Need to implement all the errors from https://docs.microsoft.com/en-us/uwp/api/windows.web.weberrorstatus
